#include <PalmOS.h>
#include "DanaQR_rsrc.h"   /* generated by pilrc from rsrc/DanaQR.rcp */
#include "chunker.h"
#include "qrcode.h"
#include "qr_render.h"
#include <Clipboard.h>

static void LoadClipboardIntoField(void) {
    MemHandle h;
    Char *clipText;
    UInt16 clipLen;
    UInt16 fldIndex;
    FieldType *fld;
    FormPtr frm;
    Char *copy;

    frm = FrmGetActiveForm();
    if (frm == NULL) return;

    fldIndex = FrmGetObjectIndex(frm, MainTextField);
    fld = (FieldType *)FrmGetObjectPtr(frm, fldIndex);
    if (fld == NULL) return;

    /* Get clipboard handle AND length in one call */
    h = ClipboardGetItem(clipboardText, &clipLen);
    if (h == NULL || clipLen == 0) {
        FrmSetFocus(frm, fldIndex);
        FldSetTextHandle(fld, NULL);
        return;
    }

    clipText = (Char *)MemHandleLock(h);
    if (clipText == NULL) return;

    /* Allocate our own buffer and copy the text */
    copy = (Char *)MemPtrNew(clipLen + 1);
    if (copy == NULL) {
        MemHandleUnlock(h);
        return;
    }

    MemMove(copy, clipText, clipLen);
    copy[clipLen] = '\0';

    /* Done with clipboard handle -- unlock but DO NOT free */
    MemHandleUnlock(h);

    FrmSetFocus(frm, fldIndex);
    FldSetTextHandle(fld, NULL);
    FldInsert(fld, copy, clipLen);

    /* Free our own copy */
    MemPtrFree(copy);
}
/* ---- App state ------------------------------------------------- */

static ChunkType sChunks[CHUNK_MAX_COUNT];
static UInt16    sChunkCount   = 0;
static UInt16    sCurChunk     = 0;
static Boolean   sCycling      = false;
static UInt32    sCycleTicks   = 0;   /* SysTicksPerSecond()-scaled */
static UInt32    sNextTickAt   = 0;

#define CYCLE_MS  1500  /* see README: tune against your scanning app */

/* ---- Forward decls ----------------------------------------------*/

static void DrawCurrentChunk(void);
static void StartCycling(void);
static void StopCycling(void);
static void RebuildChunksFromField(void);

/* ---- Form: MainForm ---------------------------------------------*/

static void DrawCurrentChunk(void)
{
    RectangleType r;
    FormType *frm = FrmGetActiveForm();
    UInt16 idx;

    if (sChunkCount == 0) {
        return;
    }

    /* QR target area: a 152x152 square in the standard 160x160
     * silkscreen region, leaving a margin above for a status label
     * (drawn separately, see StatusLabel below) and below for the
     * hardware silkscreen buttons. Adjust to match wherever you
     * actually place the qrArea in the .rcp if you change the form
     * layout. */
    r.topLeft.x = 4;
    r.topLeft.y = 20;
    r.extent.x  = 152;
    r.extent.y  = 132;

    idx = sCurChunk % sChunkCount;
    (void)QRRenderChunk(sChunks[idx].text, sChunks[idx].len, &r);

    /* Status text: "3/12" so you can tell at a glance whether the
     * scan is keeping pace, and so a manually-paused single frame is
     * identifiable. Small font, top-left corner. */
    {
        char status[16];
        StrPrintF(status, "%d/%d", idx + 1, sChunkCount);
        WinDrawChars(status, StrLen(status), 4, 4);
    }

    (void)frm;
}

static void RebuildChunksFromField(void)
{
    FormType *frm = FrmGetActiveForm();
    FieldType *fld = (FieldType *)FrmGetObjectPtr(frm,
                        FrmGetObjectIndex(frm, MainTextField));
    char *text = FldGetTextPtr(fld);
    UInt32 len = text ? StrLen(text) : 0;

    StopCycling();

    sChunkCount = ChunkerBuildChunks(text, len, sChunks, CHUNK_MAX_COUNT);
    sCurChunk = 0;

    if (sChunkCount == 0 && len > 0) {
        FrmCustomAlert(TooLongAlert, "", "", "");
        return;
    }

    if (sChunkCount > 0) {
        DrawCurrentChunk();
        StartCycling();
    }
}

static void StartCycling(void)
{
    if (sChunkCount == 0) {
        return;
    }
    sCycling = true;
    sNextTickAt = TimGetTicks() + sCycleTicks;
}

static void StopCycling(void)
{
    sCycling = false;
}

static Boolean MainFormHandleEvent(EventType *event)
{
    Boolean handled = false;

    switch (event->eType) {

    case frmOpenEvent: {
        FormType *frm = FrmGetActiveForm();
        sCycleTicks = SysTicksPerSecond() * CYCLE_MS / 1000;
        FrmDrawForm(frm);
        handled = true;
        break;
    }

    case ctlSelectEvent:
        switch (event->data.ctlSelect.controlID) {
        case GenerateButton:
            RebuildChunksFromField();
            handled = true;
            break;
        case CycleToggleButton:
            if (sCycling) {
                StopCycling();
            } else {
                StartCycling();
            }
            handled = true;
            break;
        case NextChunkButton:
            /* Manual step -- handy when a scanning app wants you to
             * pause on one frame instead of free-running the cycle. */
            StopCycling();
            if (sChunkCount > 0) {
                sCurChunk = (sCurChunk + 1) % sChunkCount;
                DrawCurrentChunk();
            }
            handled = true;
            break;
		case PasteButton:
			LoadClipboardIntoField();
			/* RebuildChunksFromField();   /* optional — auto-generate after paste */
			handled = true;
			break;
        default:
            break;
        }
        break;

    case nilEvent:
        /* Only arrives when EvtGetEvent's timeout (see PilotMain's
         * event loop) elapses -- that's how the cycling timer is
         * driven without a hardware alarm. */
        if (sCycling && sChunkCount > 0) {
            UInt32 now = TimGetTicks();
            if (now >= sNextTickAt) {
                sCurChunk = (sCurChunk + 1) % sChunkCount;
                DrawCurrentChunk();
                sNextTickAt = now + sCycleTicks;
            }
        }
        handled = true;
        break;

    default:
        break;
    }

    return handled;
}

/* ---- App-level plumbing ------------------------------------------*/

static Boolean AppHandleEvent(EventType *event)
{
    FormType *frm;
    UInt16 formId;

    if (event->eType == frmLoadEvent) {
        formId = event->data.frmLoad.formID;
        frm = FrmInitForm(formId);
        FrmSetActiveForm(frm);

        switch (formId) {
        case MainForm:
            FrmSetEventHandler(frm, MainFormHandleEvent);
            break;
        default:
            break;
        }
        return true;
    }

    return false;
}

static void AppEventLoop(void)
{
    EventType event;
    UInt16 err;

    for (;;) {
        /* Timeout of a few ticks (not "wait forever") is what lets
         * nilEvents through for the cycling timer above -- a plain
         * evtWaitForever here would starve DrawCurrentChunk() of any
         * chance to advance the frame while the user isn't touching
         * the device. */
        EvtGetEvent(&event, SysTicksPerSecond() / 10);

        if (event.eType == appStopEvent) {
            break;
        }

        SysHandleEvent(&event);
        MenuHandleEvent(0, &event, &err);
        AppHandleEvent(&event);
        FrmDispatchEvent(&event);
    }
}

static Err AppStart(void)
{
    FrmGotoForm(MainForm);
    return errNone;
}

static void AppStop(void)
{
    FrmCloseAllForms();
}

UInt32 PilotMain(UInt16 cmd, void *cmdPBP, UInt16 launchFlags)
{
    (void)cmdPBP;

    if (cmd == sysAppLaunchCmdNormalLaunch) {
        Err err = AppStart();
        if (err == errNone) {
            AppEventLoop();
        }
        AppStop();
    }

    return 0;
}
